networks:
  network_name:                       # name for network
    driver: bridge

services:
  prefix_mariadb:
    image: mariadb
    container_name: prefix_mariadb
    networks:
      - network_name
    volumes:
      - ./docker/services/mariadb/data:/var/lib/mysql
    environment:
      - TZ=America/Belem
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=vehicles_control
    restart: always
    # ports:
    #   - 7011:3306  # uncomment only if you expose your database (not recommended)

  prefix_redis:
    image: redis
    container_name: prefix_redis
    networks:
      - network_name

  prefix_golang:
    image: golang:1.22-alpine
    container_name: prefix_golang
    working_dir: /go/src/app
    networks:
      - network_name
    volumes:
      - ./backend/src/:/go/src/app
    environment:
      - TZ=America/Belem
    # command: sh ./default.sh - uncomment this line only in development mode.
    command: go run main.go
    ports:
      - 7010:9000
    depends_on:
      - prefix_mariadb
      - prefix_redis
    restart: always
  
  prefix_nginx:
    image: nginx:1.16-alpine
    container_name: prefix_nginx
    working_dir: /application
    networks:
      - network_name
    volumes:
      - ./docker/services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    # - ./services/nginx/ssl:/etc/ssl
      - ./frontend/build:/application
    environment:
      - TZ=America/Belem
    ports:
      - 7000:80
    restart: always
